positives = [
    "I want some red shoes for a wedding",
    "I'm in the mood for an action movie",
    "I want to book a trip tonight for vegas",
    "An iPhone with 32gb",
    "Who's working as an SMB in Paris?",
    "Get me to the closest bakery",
    "I'm looking for a movie with Tom Cruise",
    "A blue dress with long sleeves",
    "A book about brain science",
    "A recent book on philosophy",
    "I want to read a love novel",
    "I ate a banana and chocolate",
    "I want an athletic male in his thirties that loves hiking",
    "Is there a method to classify sentences in natural language?",
    "I need a recent car with four doors",
    "This subway is crowded, this is getting painful!",
    "I'm getting there, but we are not done",
    "How can I index blog posts?",
    "Is there a limit to the size of records?",
    "Do you have a search NLU expert available?",
    "When was Algolia founded?",
    "What's the core idea of search indexing?",
    "An analysis of coworking spaces in Paris",
    "What is the price of an expensive hotel in Paris",
    "What is the filmography of Will Smith?",
    "I am a fan of Dan Brown, what is his last book",
    "Show me blue wedding dresses",
    "Buy 3 packs of beer",
    "I need a mountainbike",
    "Where is the closest kayak renter?",
    "How is the weather in Brazil?",
    "Who is Iron man?",
    "I want to watch Marvel movies",
    "Play funky songs",
    "Find me a tasty restaurant",
    "Fly me to Taipei",
    "Teach me how to cook lasagna",
    "Instructions to make pancakes",
    "How can I make a veggie burger?",
    "Can you help me baking cookies?",
    "Should I hit my meat to tender it?",
    "What's the recipe for pho soup?",
    "Help me cook low fat fries",
    "What are the ingredients for a croziflette?",
    "How much sugar should I put in crepe dough?",
    "Find me the traditional way of preparing carbonara",
    "Help me prepare a pot au feu",
    "How long does Lasagna take to cook",
    "What do I need to make tacos",
    "How far is Beijing from paris",
    "When was Da vinci born",
    "Who plays in Iron Man",
    "How do I go to the louvre",
    "Is the Louvre open right now",
    "what are the film being released this week?",
    "what is the next availability for Louis Vuitton Exposition",
    "Which are the competitors of Nike",
    "which company will attend the iOS summit",
    "What are the biggest companies in Norway",
    "who is the most popular contemporary actress",
    "Mirror, mirror, tell me who is the most beautiful woman in the world",
    "What is water made of",
    "where do banana trees grow best?",
    "how much sugar is in a can of coca cola",
    "How much cost a kilo of banana",
    "What is the conversion between Euros and Dollars",
    "What is the capital of Venezuela",
    "what is the price of weed in San Francisco",
    "How should I wash my sheets",
    "Which football team is leading the UK league?",
    "Do I need an umbrella for Paris",
    "How do I learn how to dance",
    "what is the opening price of Jumia's IPO?",
    "Who is the president of the United States of America",
    "How do I tie a tie",
    "when is summer starting?",
    "Where should I go to the beach this summer",
    "Can you find me a supermarket",
    "where can I buy street art in paris",
    "Why does no one drink beers anymore",
    "is gymlib an expensive service?",
    "Are there hotels near the Louvre",
    "How do I make my teeth whiter",
    "Where does Cristiano Ronaldo come from",
    "what are the 5 values at Algolia",
    "How much money does a software engineer make in Paris",
    "How can I learn how to code",
    "Is travelling to Morocco banned by the american consulate?",
    "does Algolia have an office in Japan?",
    "How do I say I love you in Chinese",
    "How do I cure the common cold",
    "Is Paris dangerous in the summer",
    "Where can I stream Pirates of the Caribbean",
    "What is the best brand for watches",
    "what is the name of the son of zinedine zidane",
    "What are clouds made of",
    "What are the best shoes to go running",
    "How is the stock market today",
    "is Paul Louis Nech the richest man in the world"
]

negatives = [
    "Red wedding shoes",
    "Action movie",
    "Vegas tonight",
    "IPhone 32gb",
    "SMB Paris",
    "Closest bakery ",
    "Tom Cruise ",
    "Blue dress long sleeves",
    "Brain science",
    "Recent philosophy ",
    "Love novel",
    "One banana and chocolate",
    "Athletic male thirties hiking",
    "Classify natural language sentence",
    "Recent four doors car",
    "Crowded subway painful",
    "Getting there but not done",
    "Index blog posts",
    "Record size limit",
    "Available search NLU expert ",
    "Algolia foundation date",
    "Search indexing core idea",
    "Paris coworking space analysis",
    "Paris 5 Star hotel price",
    "Will Smith movies",
    "Dan Brown lastest book",
    "blue wedding dress",
    "beer pack",
    "mountainbike",
    "kayak rent",
    "brazil meteo",
    "Iron man name",
    "Marvel movies",
    "funk playlist",
    "tasty restaurant",
    "Taipei flight",
    "lasagna recipe",
    "pancake reciie",
    "veggie burger recipe",
    "cookie recipie",
    "tender meat",
    "pho soup recipie",
    "low fat fries recipe",
    "croziflette ingredients",
    "crepe recipie",
    "carbonara traditional recipe",
    "pot au feu recipie",
    "Lasagna Cooking Time",
    "Tacos Ingredients",
    "distance Paris beijing",
    "Da Vinci Birth Date",
    "Iron Man Casting List",
    "Go to Louvre",
    "Louvre Opening hours",
    "movie release of the week",
    "louis vuitton exposition availability ",
    "Nike Competitors ",
    "iOS summit company attendees list",
    "Norway top 5 companies",
    "contemporary actress rating",
    "Water composition",
    "ideal climate banana trees",
    "coca cola can composition",
    "price banana 1 kilo",
    "Conversion Rate Euros Dollars",
    "Venezuela capital",
    "San Francisco Weed Price",
    "Sheets laundry tips",
    "UK league standing - top result",
    "Paris weather",
    "Learn dance begginer",
    "Jumia IPO opening price",
    "USA President",
    "Tie a Tie",
    "date summer solstice",
    "Top Beach Destinations Summer",
    "Open Supermarket near me ",
    "street art shop paris",
    "Drink beers dangers",
    "price gymlib subscription",
    "Louvre hotels near",
    "White Teeth tips",
    "Cristiano Ronaldo Nationality",
    "Algolia values",
    "Software engineer average salary Paris",
    "coding lessons ",
    "ban Morocco american consulate",
    "Algolia office locations",
    "Translate I love you Chinese",
    "common cold cure",
    "Paris danger summer",
    "Pirates of the Caribbean stream",
    "top watch brands",
    "zinedine zidane son name",
    "Clouds composition",
    "running shoes best",
    "stock market today",
    "world richest man Paul louis Nech",
    "Happy shoes near me",
]
