examples_positives = [
    "I want some red shoes for a wedding",
    "I'm in the mood for an action movie",
    "I want to book a trip tonight for vegas",
    "An iPhone with 32gb",
    "Who's working as an SMB in Paris?",
    "Get me to the closest bakery",
    "I'm looking for a movie with Tom Cruse",
    "A blue dress with long sleeves",
    "A book about brain science",
    "A recent book on philosophy",
    "I want to read a love novel",
    "I ate a banana and chocolate",
    "I want an athletic male in his thirties that loves hiking",
    "Is there a method to classify sentences in natural language?",
    "I need a recent car with four doors",
    "This subway is crowded, this is getting painful!",
    "I'm getting there, but we are not done.",
    "How can I index blog posts?",
    "Is there a limit to the size of records?",
    "Do you have a search NLU expert available?",
    "When was Algolia founded?",
    "What's the core idea of search indexing?",
    "An analysis of coworking spaces in Paris",
]

examples_negatives = [
    "Red wedding shoes",
    "Action movie",
    "Vegas tonight",
    "IPhone 32gb",
    "SMB Paris",
    "Closest bakery",
    "Tom Cruse",
    "Blue dress long sleeves",
    "Brain science",
    "Recent philosophy",
    "Love novel",
    "Banana and chocolate",
    "Athletic male thirties hiking",
    "Classify natural language sentence",
    "Recent four doors car",
    "Crowded subway painful",
    "Getting there but not done",
    "Index blog posts",
    "Record size limit",
    "Available search NLU expert",
    "Algolia foundation date",
    "Search indexing core idea",
    "Paris coworking space analysis",
]

examples_all = examples_negatives + examples_positives
